//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDW56_424qEntities : DbContext
    {
        public BDW56_424qEntities()
            : base("name=BDW56_424qEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acteur> Acteurs { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<EmpruntsFilm> EmpruntsFilms { get; set; }
        public virtual DbSet<Exemplaire> Exemplaires { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Format> Formats { get; set; }
        public virtual DbSet<Langue> Langues { get; set; }
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<Producteur> Producteurs { get; set; }
        public virtual DbSet<Realisateur> Realisateurs { get; set; }
        public virtual DbSet<SousTitre> SousTitres { get; set; }
        public virtual DbSet<Supplement> Supplements { get; set; }
        public virtual DbSet<TypesUtilisateur> TypesUtilisateurs { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<UtilisateursPreference> UtilisateursPreferences { get; set; }
        public virtual DbSet<ValeursPreference> ValeursPreferences { get; set; }
    }
}
