//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpruntsFilm
    {
        public int NoExemplaire { get; set; }
        public Nullable<int> NoUtilisateur { get; set; }
        public Nullable<System.DateTime> DateEmprunt { get; set; }
    
        public virtual Exemplaire Exemplaire { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
