//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Acteurs = new HashSet<Acteur>();
            this.Langues = new HashSet<Langue>();
            this.SousTitres = new HashSet<SousTitre>();
            this.Supplements = new HashSet<Supplement>();
        }
    
        public int NoFilm { get; set; }
        public Nullable<int> AnneeSortie { get; set; }
        public Nullable<int> Categorie { get; set; }
        public Nullable<int> Format { get; set; }
        public Nullable<System.DateTime> DataMAJ { get; set; }
        public Nullable<int> NoUtilisateurMAJ { get; set; }
        public string Resume { get; set; }
        public Nullable<int> DureeMinutes { get; set; }
        public Nullable<bool> FilmOriginal { get; set; }
        public string ImagePochette { get; set; }
        public Nullable<int> NbDisques { get; set; }
        public string TitreFrancais { get; set; }
        public string TitreOriginal { get; set; }
        public Nullable<bool> VersionEtendue { get; set; }
        public Nullable<int> NoRealisateur { get; set; }
        public Nullable<int> NoProducteur { get; set; }
        public string Xtra { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Format Format1 { get; set; }
        public virtual Producteur Producteur { get; set; }
        public virtual Realisateur Realisateur { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acteur> Acteurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Langue> Langues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SousTitre> SousTitres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplement> Supplements { get; set; }
    }
}
