//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValeursPreference
    {
        public int NoUtilisateur { get; set; }
        public int NoPreference { get; set; }
        public string Valeur { get; set; }
    
        public virtual UtilisateursPreference UtilisateursPreference { get; set; }
    }
}
